### ISSUE TITLE
docker container does not exit/terminate when operations on ES fails

### ISSUE THREAD

**Issue by elipapa** [opentargets/data_pipeline#130]
@mkarmona @andreap while running the validation step of the pipeline `docker run quay.io/cttv/data_pipeline:master mrtarget --val --remote <url>` this fails: https://github.com/opentargets/data_pipeline/blob/master/mrtarget/common/ElasticsearchLoader.py#L210

The traceback is as follows:
```sh
$ docker logs 0fcfa3ac3386
validation_file_q received jobs [batch size: 1]: 0 jobs [00:00, ? jobs/s]  Traceback (most recent call last):
  File "/usr/local/bin/mrtarget", line 11, in <module>bs [00:00, ? jobs/s]
    load_entry_point('mrtarget', 'console_scripts', 'mrtarget')()0, ? jobs/s]
  File "/pipeline/source/mrtarget/CommandLine.py", line 223, in main ? jobs/s]
    increment=args.increment)obs [batch size: 1]: 0 jobs [00:00, ? jobs/s]
  File "/pipeline/source/mrtarget/modules/EvidenceValidation.py", line 1396, in check_all
    processed_datasources = file_processer.run()
  File "/pipeline/source/mrtarget/modules/EvidenceValidation.py", line 162, in run
    Config.ELASTICSEARCH_VALIDATED_DATA_INDEX_NAME + '-' + datasource))
  File "/pipeline/source/mrtarget/common/ElasticsearchLoader.py", line 201, in prepare_for_bulk_indexing
    self.es.cluster.put_settings(transient_cluster_settings)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/client/cluster.py", line 146, in put_settings
    params=params, body=body)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 327, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 84, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 113, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.AuthorizationException: TransportError(403, u'security_exception', u'action [cluster:admin/settings/update] is unauthorized for user [hannibal]')
```

Now that’s all good and dandy - I am not logged in ES without sufficient privileges, which is easy to fix. Just give more privileges to the `hannibal` user. 

The **real** issue is that the docker container does not terminate. Logging into the container with `docker exec -ti 0fcfa3ac3386 bash` and running `ps aux` shows a bunch of seemingly equivalent processes:

```sh
root@ip-172-31-17-2:/usr/src/app# ps aux
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root          1  1.1  1.4 1964916 966804 ?      Ssl  May23  10:50 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         29  0.1  1.5 1079064 1052356 ?     Ssl  May23   1:29 /usr/local/lib/python2.7/site-packages/redislite/bin/redis-server *:0
root         32  0.0  1.4 1964916 939188 ?      Sl   May23   0:21 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         34  0.0  1.4 1965684 937304 ?      Sl   May23   0:08 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         36  0.0  1.4 1965428 937048 ?      Sl   May23   0:08 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         38  0.0  1.4 1965428 937048 ?      Sl   May23   0:08 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         40  0.0  1.4 1965428 937048 ?      Sl   May23   0:08 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         42  0.0  1.4 1965428 937048 ?      Sl   May23   0:08 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         44  0.0  1.4 1965428 937048 ?      Sl   May23   0:09 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         46  0.0  1.4 1965428 937048 ?      Sl   May23   0:09 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         48  0.0  1.4 1965428 937040 ?      Sl   May23   0:09 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         50  0.0  1.4 1965428 937048 ?      Sl   May23   0:09 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         52  0.0  1.4 1965428 937048 ?      Sl   May23   0:09 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         54  0.0  1.4 1965428 937048 ?      Sl   May23   0:08 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         56  0.0  1.4 1965428 937048 ?      Sl   May23   0:08 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         58  0.0  1.4 1965428 937048 ?      Sl   May23   0:08 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         60  0.0  1.4 1965428 937048 ?      Sl   May23   0:09 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         62  0.0  1.4 1965428 937048 ?      Sl   May23   0:09 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         64  0.0  1.4 1965428 937048 ?      Sl   May23   0:09 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         66  0.0  1.4 1965428 937048 ?      Sl   May23   0:09 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         68  0.0  1.4 1965428 937028 ?      Sl   May23   0:09 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         70  0.0  1.4 1965428 937044 ?      Sl   May23   0:09 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         72  0.0  1.4 1965428 937044 ?      Sl   May23   0:09 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         74  0.0  1.4 1965428 937044 ?      Sl   May23   0:09 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         76  0.0  1.4 1965428 937028 ?      Sl   May23   0:09 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         78  0.0  1.4 1965428 937040 ?      Sl   May23   0:09 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         80  0.0  1.4 1965428 937048 ?      Sl   May23   0:08 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         82  0.0  1.4 1965428 937048 ?      Sl   May23   0:08 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         84  0.0  1.4 1965428 937048 ?      Sl   May23   0:08 /usr/local/bin/python /usr/local/bin/mrtarget --val --remote-file https://storage.googleapis.com/otar
root         93  0.0  0.0  21948  3628 ?        Ss   10:07   0:00 bash
root         99  0.0  0.0  19188  2340 ?        R+   10:08   0:00 ps aux
```
None of these processes appear to consume much memory or CPU, so I am assuming they are apparently stuck. 

Shouldn't an exception like the above raise a `sys.exit`? Is this a problem with the redis workers spun by the job queue?

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #177](https://github.com/opentargets/platform/issues/177) via [**ZenHub**](https://www.zenhub.com/)
