### ISSUE TITLE
Error while running --sea (Search Data Processing) step

### ISSUE THREAD

**Issue by pieterlukasse** [opentargets/data_pipeline#264]
My processing stops at `--sea` step. It crashes with following errors:
```
2018-04-17 13:36:13,316 - __main__ - INFO - setting schema version string to master
  {
      "analysis": {
          "analyzer": {
              "edgeNGram_analyzer": {
                  "filter": [
                      "lowercase", 
                      "asciifolding", 
                      "wordDelimiter_filter", 
                      "edgeNGram_filter"
                  ], 
                  "tokenizer": "whitespace", 
                  "type": "custom"
              }, 
              "onechunk_analyzer": {
                  "filter": [
                      "lowercase", 
                      "asciifolding", 
                      "simple_filter", 
                      "fingerprint"
                  ], 
                  "tokenizer": "keyword", 
                  "type": "custom"
              }, 
              "whitespace_analyzer": {
                  "filter": [
                      "lowercase", 
                      "asciifolding", 
                      "simple_filter"
                  ], 
                  "tokenizer": "whitespace", 
                  "type": "custom"
              }
          }, 
          "filter": {
              "edgeNGram_filter": {
                  "max_gram": "10", 
                  "min_gram": "2", 
                  "token_chars": [
                      "letter", 
                      "digit", 
                      "punctuation"
                  ], 
                  "type": "edgeNGram"
              }, 
              "simple_filter": {
                  "token_chars": [
                      "letter", 
                      "digit"
                  ], 
                  "type": "standard"
              }, 
              "wordDelimiter_filter": {
-                 "catenate_all": "false", 
?                                 -     -
+                 "catenate_all": false, 
-                 "catenate_numbers": "false", 
?                                     -     -
+                 "catenate_numbers": false, 
-                 "catenate_words": "false", 
?                                   -     -
+                 "catenate_words": false, 
-                 "generate_number_parts": "true", 
?                                          -    -
+                 "generate_number_parts": true, 
-                 "generate_word_parts": "true", 
?                                        -    -
+                 "generate_word_parts": true, 
-                 "preserve_original": "true", 
?                                      -    -
+                 "preserve_original": true, 
-                 "split_on_case_change": "false", 
?                                         -     -
+                 "split_on_case_change": false, 
-                 "split_on_numerics": "false", 
?                                      -     -
+                 "split_on_numerics": false, 
-                 "stem_english_possessive": "true", 
?                                            -    -
+                 "stem_english_possessive": true, 
                  "type": "word_delimiter"
              }
          }
      }, 
      "number_of_replicas": "0", 
      "number_of_shards": "1", 
      "refresh_interval": "60s"
  }2018-04-17 13:36:13,390 - mrtarget.common.ElasticsearchLoader - ERROR - elasticsearch settings error
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/mrtarget/common/ElasticsearchLoader.py", line 267, in _safe_create_index
    keys=body['settings'].keys(),#['number_of_replicas','number_of_shards','refresh_interval']
  File "build/bdist.linux-x86_64/egg/mrtarget/common/EvidenceJsonUtils.py", line 26, in assertJSONEqual
    raise ValueError(msg)
ValueError: settings in elasticsearch are different from the ones sent
2018-04-17 13:36:13,390 - mrtarget.common.ElasticsearchLoader - INFO - 17.12_search-data index created
2018-04-17 13:36:13,393 - mrtarget.common.LookupHelpers - INFO - get chembl_drugs info
2018-04-17 13:36:13,394 - mrtarget.common.LookupHelpers - INFO - loading lookup data:   0%|          | 0/1 [00:00<?, ? steps/s]
2018-04-17 13:36:13,394 - mrtarget.common.Redis - INFO - reporter worker started
2018-04-17 13:36:13,395 - mrtarget.common.Redis - INFO - search_obj_processing received jobs [batch size: 1]: 0 jobs [00:00, ? jobs/s]
2018-04-17 13:36:13,396 - mrtarget.common.Redis - INFO - 
2018-04-17 13:36:13,396 - mrtarget.common.Redis - INFO - search_obj_processing processed jobs [batch size: 1]: 0 jobs [00:00, ? jobs/s]
2018-04-17 13:36:13,528 - mrtarget.common.LookupHelpers - INFO - 
Traceback (most recent call last):
  File "mrtarget/CommandLine.py", line 336, in <module>
    sys.exit(main())
  File "mrtarget/CommandLine.py", line 316, in main
    skip_diseases=args.skip_diseases)
  File "build/bdist.linux-x86_64/egg/mrtarget/modules/SearchObjects.py", line 300, in process_all
  File "build/bdist.linux-x86_64/egg/mrtarget/common/LookupHelpers.py", line 131, in __init__
  File "build/bdist.linux-x86_64/egg/mrtarget/common/LookupHelpers.py", line 257, in _get_available_chembl_mappings
  File "build/bdist.linux-x86_64/egg/mrtarget/modules/ChEMBL.py", line 215, in _populate_synonyms_for_molecule
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.ebi.ac.uk/chembl/api/data/molecule/set/.json
```
The last one seems like a bug:
```
404 Client Error: Not Found for url: https://www.ebi.ac.uk/chembl/api/data/molecule/set/.json
```
### Steps to reproduce:

1. setup new OT elasticsearch with 17.12 snapshot (https://console.cloud.google.com/storage/browser/open-targets-data-releases/17.12/17.12_snapshot/)
2. delete the following indexes (goal is to generate them again):
```
curl -XDELETE localhost:9200/17.12_evidence-data-generic
curl -XDELETE localhost:9200/17.12_association-data
curl -XDELETE localhost:9200/17.12_search-data
curl -XDELETE localhost:9200/17.12_relation-data
```
3. Download and Load/validate some evidence strings from https://console.cloud.google.com/storage/browser/ot-releases/17.12/:
```
python2.7 mrtarget/CommandLine.py --val --log-level DEBUG 17.12 --schema-version 1.2.7 --input-file ~/Downloads/17.12_reactome-17-11-2017.json.gz | tee output_reactome.log
python2.7 mrtarget/CommandLine.py --val --log-level DEBUG 17.12 --schema-version 1.2.7 --input-file ~/Downloads/17.12_cosmic-14-11-2017.json.gz | tee output_cosmic.log
```
4. Run Evidence string processing:
```
python2.7 mrtarget/CommandLine.py --evs --log-level INFO 17.12 | tee output_evs.log
```
5. Run Association score calculation:
```
python2.7 mrtarget/CommandLine.py --as --log-level INFO 17.12 | tee output_as.log
```
6. Run QC:
```
python2.7 mrtarget/CommandLine.py --qc --log-level INFO 17.12 | tee output_qc.log
Result:
INFO - no missing annotation found
2018-04-17 13:35:12,677 - __main__ - INFO - it was correctly executed - finished
```
7. Run Search data processing:
```
python2.7 mrtarget/CommandLine.py --sea --log-level INFO 17.12 | tee output_sea.log
```
This last steps fails with the error reported in this issue.

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #169](https://github.com/opentargets/platform/issues/169) via [**ZenHub**](https://www.zenhub.com/)
